### ISSUE TITLE
Should a User be able to have access to any channel? 

### ISSUE THREAD

**Issue by Alxttar** [Pirey96/Project-341#28]
Should the channels all public or when usr connects to a group he can only access this group's channels? Same goes for users should all user be visible to the other users, or should they only be visible to the group?

**Comment by HanfordWu** [comment]
So far we don't have groups, all users are the same group, so I think all channels should be public, and all users are visible to other users.

**Comment by Alxttar** [comment]
After discussing it with the group here are the rules we decided:
- The general channel will be automatically joined by all the new users.
- The create of a new channel will be automatically added to the channel.
- If user wants to join specific channel he need to search for that channel.
- if channel is private only can join by request.
